## 자바와 코틀린간 예외처리
### 자바에서 코틀린 예외 다루기
- 자바에선 체크드 익셉션이 발생할 경우 try-catch를 사용하거나 예외를 전파해야함
```java
public class Main {

    public void throwIOE() throws IOException{
        throw new IOException("체크드 익셉션 발생");
    }
    public static void main(String[] args) {
        Main m = new Main();

        try {
            m.throwIOE();
        } catch (IOException e) {
            e.printStackTrace();
        }
    }
}
```

- 코틀린은 체크드 익셉션이 존재하지 않음
- IOE 발생가능한 코드를 사용해도 try-catch를 강제하진 않음
```kotlin
class KotlinThrow{
    fun throwIOE(){
        throw IOException("체크드 익셉션 발생")
    }
}

fun main(){
    val main = Main()
    main.throwIOE()

    val kotlinThrow = KotlinThrow()
    kotlinThrow.throwIOE()
}
```

- 역으로 자바에서 코틀린의 IOE가 발생 가능한 코드를 사용해도 예외처리를 강제하진 않음
  - try-catch 를 강제하지 않음
  - 오히려 try-catch 를 사용하는 경우 컴파일오류
```java
    public static void main(String[] args) {
        KotlinThrow kotlinThrow = new KotlinThrow();

        kotlinThrow.throwIOE();
    }
```

- 자바에서 사용 할 때 예외처리를 강제하고 싶은경우 @Throws 어노테이션 사용
```kotlin
class KotlinThrow{
    @Throws(IOException::class)
    fun throwIOE(){
        throw IOException("체크드 익셉션 발생")
    }
}
```